import { useEffect, useMemo, useRef, useState } from 'react';
import { request, formatDateTime } from './api';
import { Icon } from './Icons';

const COPY = {
  en: { title:'Book an appointment', duration:'Choose duration', time:'Choose a time', details:'Your details', confirm:'Confirm booking', recheck:'Availability is checked again when you confirm.', name:'Full name', email:'Email address', manage:'Manage booking', reschedule:'Reschedule', cancel:'Cancel', reminder:'Google Calendar sends the configured reminders.', noSlots:'No available times for this date.', success:'Your appointment is confirmed.' },
  nl: { title:'Boek een afspraak', duration:'Kies de duur', time:'Kies een tijd', details:'Jouw gegevens', confirm:'Afspraak bevestigen', recheck:'De beschikbaarheid wordt opnieuw gecontroleerd wanneer je bevestigt.', name:'Volledige naam', email:'E-mailadres', manage:'Afspraak beheren', reschedule:'Verplaatsen', cancel:'Annuleren', reminder:'Google Agenda verstuurt de ingestelde herinneringen.', noSlots:'Geen beschikbare tijden op deze datum.', success:'Je afspraak is bevestigd.' }
};

function localDate(offset=1){const date=new Date();date.setDate(date.getDate()+offset);return date.toISOString().slice(0,10);}

function ErrorMessage({ error }) { return error ? <div className="alert error" role="alert"><strong>{error.message}</strong><span>{error.retryable?' You can safely retry.':' Review your selection before trying again.'}</span></div> : null; }

function ManageBooking({ bookingId, token, locale, onExit }) {
  const [booking,setBooking]=useState(null); const [error,setError]=useState(null); const [working,setWorking]=useState(false); const [date,setDate]=useState(localDate()); const [slots,setSlots]=useState([]); const [selected,setSelected]=useState(null);
  useEffect(()=>{request(`/api/public/bookings/${bookingId}/manage`,{method:'POST',body:JSON.stringify({token})}).then((result)=>setBooking(result.booking)).catch(setError);},[bookingId,token]);
  const duration=booking?Math.round((new Date(booking.end)-new Date(booking.start))/60000):0;
  const findTimes=async()=>{setWorking(true);setError(null);try{const result=await request(`/api/public/schedules/${encodeURIComponent(booking.schedule.slug)}/slots?duration=${duration}&from=${date}&to=${date}`);setSlots(result.slots);}catch(err){setError(err);}finally{setWorking(false);}};
  const reschedule=async()=>{if(!selected)return;setWorking(true);setError(null);try{const result=await request(`/api/public/bookings/${bookingId}/reschedule`,{method:'POST',body:JSON.stringify({token,start:selected.start})});setBooking(result.booking);setSlots([]);setSelected(null);}catch(err){setError(err);}finally{setWorking(false);}};
  const cancel=async()=>{if(!window.confirm('Cancel this booking? Google Calendar and the requester will be updated.'))return;setWorking(true);setError(null);try{const result=await request(`/api/public/bookings/${bookingId}/cancel`,{method:'POST',body:JSON.stringify({token})});setBooking(result.booking);}catch(err){setError(err);}finally{setWorking(false);}};
  if(!booking)return <main className="booking-shell"><ErrorMessage error={error}/><p>Loading booking…</p></main>;
  return <main className="booking-shell manage"><div className="booking-top"><div className="brand"><Icon name="calendar"/><strong>Chronological Booking</strong></div><button className="text-button" onClick={onExit}>Book another appointment</button></div><section className="manage-panel"><h1>{COPY[locale].manage}</h1><dl><div><dt>Schedule</dt><dd>{booking.schedule.name}</dd></div><div><dt>Date & time</dt><dd>{formatDateTime(booking.start,locale)}</dd></div><div><dt>Status</dt><dd><span className={`state ${booking.status}`}>{booking.status}</span></dd></div><div><dt>Email</dt><dd>{booking.requesterEmail}</dd></div></dl><div className="info-note"><Icon name="calendar"/>Availability is checked again before rescheduling. Cancellation is applied to Google Calendar immediately.</div>{booking.status==='confirmed'?<div className="reschedule-box"><label>New date<input type="date" min={localDate(0)} value={date} onChange={(event)=>setDate(event.target.value)}/></label><button className="secondary" onClick={findTimes} disabled={working}>Find available times</button>{slots.length?<div className="slot-list">{slots.map((item)=><button type="button" className={selected?.start===item.start?'selected':''} key={item.start} onClick={()=>setSelected(item)}>{formatDateTime(item.start,locale)}</button>)}</div>:null}<button className="primary" disabled={!selected||working} onClick={reschedule}>{COPY[locale].reschedule}</button></div>:null}<ErrorMessage error={error}/><button className="danger" disabled={working||booking.status==='cancelled'} onClick={cancel}>{COPY[locale].cancel}</button></section></main>;
}

export function BookingPage({ slug }) {
  const params=useMemo(()=>new URLSearchParams(window.location.hash.replace(/^#/,'')),[]); const manageId=params.get('manage'); const manageToken=params.get('token'); const idempotencyKey=useRef(crypto.randomUUID());
  const [locale,setLocale]=useState('en'); const [schedule,setSchedule]=useState(null); const [duration,setDuration]=useState(null); const [date,setDate]=useState(localDate()); const [slots,setSlots]=useState([]); const [slot,setSlot]=useState(null); const [details,setDetails]=useState({name:'',email:''}); const [accepted,setAccepted]=useState(false); const [error,setError]=useState(null); const [working,setWorking]=useState(false); const [confirmed,setConfirmed]=useState(null);
  const t=COPY[locale];
  useEffect(()=>{if(manageId)return;request(`/api/public/schedules/${encodeURIComponent(slug)}`).then(({schedule:next})=>{setSchedule(next);setDuration(next.durations[0]);}).catch(setError);},[slug,manageId]);
  useEffect(()=>{if(!duration||!date||manageId)return;setSlot(null);setSlots([]);setError(null);request(`/api/public/schedules/${encodeURIComponent(slug)}/slots?duration=${duration}&from=${date}&to=${date}`).then((result)=>setSlots(result.slots)).catch(setError);},[slug,duration,date,manageId]);
  if(manageId&&manageToken)return <ManageBooking bookingId={manageId} token={manageToken} locale={locale} onExit={()=>window.location.assign(`/book/${slug}`)}/>;
  const submit=async(event)=>{event.preventDefault();if(!slot||!accepted)return;setWorking(true);setError(null);try{const result=await request(`/api/public/schedules/${encodeURIComponent(slug)}/book`,{method:'POST',headers:{'idempotency-key':idempotencyKey.current},body:JSON.stringify({...details,duration,start:slot.start})});setConfirmed(result.booking);}catch(err){setError(err);if(err.code==='SLOT_UNAVAILABLE'){setSlot(null);idempotencyKey.current=crypto.randomUUID();}}finally{setWorking(false);}};
  if(!schedule&&!error)return <main className="booking-shell"><p>Loading booking page…</p></main>;
  if(confirmed)return <main className="booking-shell"><div className="booking-top"><div className="brand"><Icon name="calendar"/><strong>Chronological Booking</strong></div></div><section className="success-panel"><div className="success-icon"><Icon name="check" size={30}/></div><h1>{t.success}</h1><p>{schedule.name} · {formatDateTime(confirmed.start,locale)}</p><p>Google Calendar has been updated and reminders are handled by Google.</p><a className="primary button-link" href={confirmed.manageUrl}>{t.manage}</a></section></main>;
  return <main className="booking-shell"><div className="booking-top"><div className="brand"><Icon name="calendar"/><strong>Chronological Booking</strong></div><div className="language"><Icon name="globe" size={18}/><button className={locale==='nl'?'active':''} onClick={()=>setLocale('nl')}>Nederlands</button><span>/</span><button className={locale==='en'?'active':''} onClick={()=>setLocale('en')}>English</button></div></div><h1>{t.title}</h1>{schedule?<p className="booking-intro">{schedule.name}{schedule.location?` · ${schedule.location}`:''} · {schedule.timezone}</p>:null}<ErrorMessage error={error}/>
    {schedule?<form className="booking-grid" onSubmit={submit}><section className="booking-step"><div className="step-title"><span>1</span><div><h2>{t.duration}</h2><p>Select how much time you need.</p></div></div><div className="duration-list">{schedule.durations.map((value)=><label className={duration===value?'selected':''} key={value}><input type="radio" name="duration" checked={duration===value} onChange={()=>setDuration(value)}/><strong>{value} minutes</strong></label>)}</div><div className="info-note">You can change this until confirmation.</div></section>
      <section className="booking-step"><div className="step-title"><span>2</span><div><h2>{t.time}</h2><p>Times are shown in {schedule.timezone}.</p></div></div><label>Date<input type="date" min={localDate(0)} value={date} onChange={(event)=>setDate(event.target.value)} /></label><div className="slot-list" aria-live="polite">{slots.map((item)=><button type="button" className={slot?.start===item.start?'selected':''} key={item.start} onClick={()=>setSlot(item)}>{new Intl.DateTimeFormat(locale==='nl'?'nl-NL':'en-GB',{hour:'2-digit',minute:'2-digit',timeZone:schedule.timezone}).format(new Date(item.start))}{slot?.start===item.start?<Icon name="check" size={17}/>:null}</button>)}{!slots.length&&!error?<p className="empty">{t.noSlots}</p>:null}</div></section>
      <section className="booking-step review"><div className="step-title"><span>3</span><div><h2>{t.details}</h2><p>Review and confirm.</p></div></div><label>{t.name}<input value={details.name} onChange={(event)=>setDetails({...details,name:event.target.value})} required minLength="2" /></label><label>{t.email}<input type="email" value={details.email} onChange={(event)=>setDetails({...details,email:event.target.value})} required /></label><div className="summary"><h3>Booking summary</h3><dl><div><dt>Duration</dt><dd>{duration} minutes</dd></div><div><dt>Date & time</dt><dd>{slot?formatDateTime(slot.start,locale):'Choose a time'}</dd></div><div><dt>Time zone</dt><dd>{schedule.timezone}</dd></div><div><dt>Reminder</dt><dd>{t.reminder}</dd></div></dl></div><div className="info-note strong"><Icon name="calendar"/>{t.recheck}</div><label className="checkbox"><input type="checkbox" checked={accepted} onChange={(event)=>setAccepted(event.target.checked)} required/> I have reviewed the details and consent to creating this Google Calendar appointment.</label><button className="primary confirm" disabled={!slot||!accepted||working}>{working?'Checking availability…':t.confirm}</button></section></form>:null}
    <section className="manage-strip"><div><h2>{t.manage}</h2><p>Use the private link from your booking confirmation to reschedule or cancel.</p></div><span><Icon name="calendar"/> Private token required</span></section></main>;
}
